version: '3'
services:
  postgres:
    container_name: db
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data # persist data even if container shuts downvolumes:
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
volumes:
  pgdata:
    external: false