name: Build

# bei jedem Change auf einem Branch → Bauen + Testen
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with maven
        run: mvn --batch-mode clean test
